//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.19 at 02:46:29 PM ART 
//


package org.mule.modules.quickbooks.schema.online;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CdmCollections complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CdmCollections">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.intuit.com/sb/cdm/v2}CdmComplexBase">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CdmCollections")
@XmlSeeAlso({
    BillPayments.class,
    Customers.class,
    Classes.class,
    Vendors.class,
    SalesReps.class,
    CreditCardCredits.class,
    CompaniesMetaData.class,
    Employees.class,
    VendorCredits.class,
    CashPurchases.class,
    Checks.class,
    SalesTerms.class,
    TimeActivities.class,
    Items.class,
    Discounts.class,
    ItemReceipts.class,
    InventoryAdjustments.class,
    Estimates.class,
    ShipMethods.class,
    SalesTaxPaymentChecks.class,
    CreditCardCharges.class,
    VendorCreditsToApply.class,
    SalesOrders.class,
    JournalEntries.class,
    Invoices.class,
    CreditMemos.class,
    TxnGenerics.class,
    SalesTaxCodes.class,
    UOMs.class,
    Payments.class,
    Bills.class,
    SalesReceipts.class,
    SalesTaxes.class,
    SalesTaxGroups.class,
    Jobs.class,
    Charges.class,
    PurchaseOrders.class,
    Accounts.class,
    PaymentMethods.class,
    QboAccountTypeEnums.class
})
public abstract class CdmCollections
    extends CdmComplexBase
{


}
