//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.19 at 02:46:29 PM ART 
//


package org.mule.modules.quickbooks.schema.online;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Used to request a list report (see enum for the types encompassed by that).
 *                 For now, no customization...but that will change.
 * 
 * <p>Java class for QboListReportRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QboListReportRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ListReport" type="{http://www.intuit.com/sb/cdm/qboReports}QboListReportsEnum"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QboListReportRequest", namespace = "http://www.intuit.com/sb/cdm/qboReports", propOrder = {
    "listReport"
})
public class QboListReportRequest {

    @XmlElement(name = "ListReport", required = true)
    protected QboListReportsEnum listReport;

    /**
     * Gets the value of the listReport property.
     * 
     * @return
     *     possible object is
     *     {@link QboListReportsEnum }
     *     
     */
    public QboListReportsEnum getListReport() {
        return listReport;
    }

    /**
     * Sets the value of the listReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link QboListReportsEnum }
     *     
     */
    public void setListReport(QboListReportsEnum value) {
        this.listReport = value;
    }

}
