/**
 * Mule QuickBooks Connector
 *
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.15 at 05:31:44 PM GMT-03:00 
//


package org.mule.modules.quickbooks.windows.schema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Product: QBO
 *         Description: The Bill represents an expense to the business. An expense is of the following types: [li] Item-based expense for the item that the business owner purchases for resale. [/li][li]  Account-based expense for the amount that the business owner spends on an account, such as expense incurred on the Advertisement Expense account.[/li]
 *         EndPoint: qbo.intuit.com
 *         Business Rules: [li]If an account is provided in the header of the bill, it must be the Account Payable (AP) account. [li] A bill must have reference to a vendor in the header.[/li] [li] A bill must have at least one line that describes the item or account.[/li] [li] A bill must have reference to an entity.[/li]        
 *         Product: QBW
 *         Description: Bill is an AP transaction representing a request-for-payment from a third party for goods/services rendered and/or received. Bill is a request for payment from the vendor for the goods or services that are rendered. You can enter a bill for your expenses or the items that you track as part of your business. An item is anything that your company buys, sells, or resells in the course of business. For example, products, shipping and handling charges, discounts, and sales tax. [br/] An expense is the amount of money that you spend on the items that you want to buy. Expenses are linked to expense accounts. For example, if you pay $200 per month for utilities, you can set up an expense account for these utilities, and assign the bill to this account.
 *         EndPoint: services.intuit.com
 *         Business Rules: [li]If an account is provided in the header of the bill, it must be the Account Payable (AP) account. [/li][li] A bill must have reference to a vendor in the header. [/li][li] A bill must have at least one line that describes the item or account. [/li][li] A bill must have reference to an entity.[/li]        
 *       
 * 
 * <p>Java class for Bill complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Bill">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.intuit.com/sb/cdm/v2}CdmBase">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{http://www.intuit.com/sb/cdm/v2}BillHeader" minOccurs="0"/>
 *         &lt;element name="Line" type="{http://www.intuit.com/sb/cdm/v2}BillLine" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Bill", propOrder = {
    "header",
    "line"
})
public class Bill
    extends CdmBase
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Header")
    protected BillHeader header;
    @XmlElement(name = "Line")
    protected List<BillLine> line;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link BillHeader }
     *     
     */
    public BillHeader getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillHeader }
     *     
     */
    public void setHeader(BillHeader value) {
        this.header = value;
    }

    /**
     * Gets the value of the line property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the line property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BillLine }
     * 
     * 
     */
    public List<BillLine> getLine() {
        if (line == null) {
            line = new ArrayList<BillLine>();
        }
        return this.line;
    }

    /**
     * Sets the value of the line property.
     * 
     * @param line
     *     allowed object is
     *     {@link BillLine }
     *     
     */
    public void setLine(List<BillLine> line) {
        this.line = line;
    }

}
