/**
 * Mule QuickBooks Connector
 *
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.15 at 05:31:44 PM GMT-03:00 
//


package org.mule.modules.quickbooks.windows.schema;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CurrencyFormatInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CurrencyFormatInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DecimalPlaces" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="DecimalSeparator" type="{http://www.intuit.com/sb/cdm/v2}separatorEnum" minOccurs="0"/>
 *         &lt;element name="ValueGroupSeparator" type="{http://www.intuit.com/sb/cdm/v2}separatorEnum" minOccurs="0"/>
 *         &lt;element name="ValueGrouping" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CurrencyFormatInfo", propOrder = {
    "decimalPlaces",
    "decimalSeparator",
    "valueGroupSeparator",
    "valueGrouping"
})
public class CurrencyFormatInfo
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "DecimalPlaces")
    protected Integer decimalPlaces;
    @XmlElement(name = "DecimalSeparator")
    protected SeparatorEnum decimalSeparator;
    @XmlElement(name = "ValueGroupSeparator")
    protected SeparatorEnum valueGroupSeparator;
    @XmlElement(name = "ValueGrouping")
    protected String valueGrouping;

    /**
     * Gets the value of the decimalPlaces property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDecimalPlaces() {
        return decimalPlaces;
    }

    /**
     * Sets the value of the decimalPlaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDecimalPlaces(Integer value) {
        this.decimalPlaces = value;
    }

    /**
     * Gets the value of the decimalSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link SeparatorEnum }
     *     
     */
    public SeparatorEnum getDecimalSeparator() {
        return decimalSeparator;
    }

    /**
     * Sets the value of the decimalSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeparatorEnum }
     *     
     */
    public void setDecimalSeparator(SeparatorEnum value) {
        this.decimalSeparator = value;
    }

    /**
     * Gets the value of the valueGroupSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link SeparatorEnum }
     *     
     */
    public SeparatorEnum getValueGroupSeparator() {
        return valueGroupSeparator;
    }

    /**
     * Sets the value of the valueGroupSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeparatorEnum }
     *     
     */
    public void setValueGroupSeparator(SeparatorEnum value) {
        this.valueGroupSeparator = value;
    }

    /**
     * Gets the value of the valueGrouping property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueGrouping() {
        return valueGrouping;
    }

    /**
     * Sets the value of the valueGrouping property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueGrouping(String value) {
        this.valueGrouping = value;
    }

}
