/**
 * Mule QuickBooks Connector
 *
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.15 at 05:31:44 PM GMT-03:00 
//


package org.mule.modules.quickbooks.windows.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for operatorEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="operatorEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="GT"/>
 *     &lt;enumeration value="GTE"/>
 *     &lt;enumeration value="LT"/>
 *     &lt;enumeration value="LTE"/>
 *     &lt;enumeration value="EQ"/>
 *     &lt;enumeration value="XEQ"/>
 *     &lt;enumeration value="CT"/>
 *     &lt;enumeration value="XCT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "operatorEnumType")
@XmlEnum
public enum OperatorEnumType {


    /**
     * 
     *             Product: QBW
     *             Description: Greater Than, applies to Dates as well.
     *           
     * 
     */
    GT,

    /**
     * 
     *             Product: QBW
     *             Description: Greater Than Or Equal, applies to Dates as well.
     *           
     * 
     */
    GTE,

    /**
     * 
     *             Product: QBW
     *             Description: Less Than, applies to Dates as well.
     *           
     * 
     */
    LT,

    /**
     * 
     *             Product: QBW
     *             Description: Less Than Or Equal, applies to Dates as well.
     *           
     * 
     */
    LTE,

    /**
     * 
     *             Product: QBW
     *             Description: Equal, applies to Dates as well.
     *           
     * 
     */
    EQ,

    /**
     * 
     *             Product: QBW
     *             Description: Not Equal, applies to Dates as well.
     *           
     * 
     */
    XEQ,

    /**
     * 
     *             Product: QBW
     *             Description: Contains.
     *           
     * 
     */
    CT,

    /**
     * 
     *             Product: QBW
     *             Description: Does Not Contain.
     *           
     * 
     */
    XCT;

    public String value() {
        return name();
    }

    public static OperatorEnumType fromValue(String v) {
        return valueOf(v);
    }

}
