/**
 * Mule QuickBooks Connector
 *
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.15 at 05:31:44 PM GMT-03:00 
//


package org.mule.modules.quickbooks.windows.schema;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Product: QBW 
 * 				Description: A non-wage payroll item is used to track individual amounts on a paycheck for taxes, saving plan (401K) contributions, direct-deposit amounts - items other than wage, salary, commission, or bonus. You can assign these payroll items to various accounts. For wage-based payroll items, see PayrollItem.
 * 			
 * 
 * <p>Java class for PayrollNonWageItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PayrollNonWageItem">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.intuit.com/sb/cdm/v2}CdmBase">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Active" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Type" type="{http://www.intuit.com/sb/cdm/v2}PayrollNonWageItemTypeEnum" minOccurs="0"/>
 *         &lt;element name="ExpenseAccountId" type="{http://www.intuit.com/sb/cdm/v2}IdType" minOccurs="0"/>
 *         &lt;element name="ExpenseAccountName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LiabilityAccountId" type="{http://www.intuit.com/sb/cdm/v2}IdType" minOccurs="0"/>
 *         &lt;element name="LiabilityAccountName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PayrollNonWageItem", propOrder = {
    "name",
    "active",
    "type",
    "expenseAccountId",
    "expenseAccountName",
    "liabilityAccountId",
    "liabilityAccountName"
})
public class PayrollNonWageItem
    extends CdmBase
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Active")
    protected Boolean active;
    @XmlElement(name = "Type")
    protected PayrollNonWageItemTypeEnum type;
    @XmlElement(name = "ExpenseAccountId")
    protected IdType expenseAccountId;
    @XmlElement(name = "ExpenseAccountName")
    protected String expenseAccountName;
    @XmlElement(name = "LiabilityAccountId")
    protected IdType liabilityAccountId;
    @XmlElement(name = "LiabilityAccountName")
    protected String liabilityAccountName;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the active property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setActive(Boolean value) {
        this.active = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link PayrollNonWageItemTypeEnum }
     *     
     */
    public PayrollNonWageItemTypeEnum getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayrollNonWageItemTypeEnum }
     *     
     */
    public void setType(PayrollNonWageItemTypeEnum value) {
        this.type = value;
    }

    /**
     * Gets the value of the expenseAccountId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getExpenseAccountId() {
        return expenseAccountId;
    }

    /**
     * Sets the value of the expenseAccountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setExpenseAccountId(IdType value) {
        this.expenseAccountId = value;
    }

    /**
     * Gets the value of the expenseAccountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpenseAccountName() {
        return expenseAccountName;
    }

    /**
     * Sets the value of the expenseAccountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpenseAccountName(String value) {
        this.expenseAccountName = value;
    }

    /**
     * Gets the value of the liabilityAccountId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getLiabilityAccountId() {
        return liabilityAccountId;
    }

    /**
     * Sets the value of the liabilityAccountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setLiabilityAccountId(IdType value) {
        this.liabilityAccountId = value;
    }

    /**
     * Gets the value of the liabilityAccountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLiabilityAccountName() {
        return liabilityAccountName;
    }

    /**
     * Sets the value of the liabilityAccountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLiabilityAccountName(String value) {
        this.liabilityAccountName = value;
    }

}
