/**
 * Mule QuickBooks Connector
 *
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.15 at 05:31:44 PM GMT-03:00 
//


package org.mule.modules.quickbooks.windows.schema;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SearchRestResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchRestResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MetaData" type="{http://www.intuit.com/sb/cdm/v2}MetaData"/>
 *         &lt;element name="SearchDocs" type="{http://www.intuit.com/sb/cdm/v2}SearchDocs"/>
 *         &lt;element name="EntityCollection" type="{http://www.intuit.com/sb/cdm/v2}EntityCollection"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchRestResponse", propOrder = {
    "metaData",
    "searchDocs",
    "entityCollection"
})
public class SearchRestResponse
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "MetaData", required = true)
    protected MetaData metaData;
    @XmlElement(name = "SearchDocs", required = true)
    protected SearchDocs searchDocs;
    @XmlElement(name = "EntityCollection", required = true)
    protected EntityCollection entityCollection;

    /**
     * Gets the value of the metaData property.
     * 
     * @return
     *     possible object is
     *     {@link MetaData }
     *     
     */
    public MetaData getMetaData() {
        return metaData;
    }

    /**
     * Sets the value of the metaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaData }
     *     
     */
    public void setMetaData(MetaData value) {
        this.metaData = value;
    }

    /**
     * Gets the value of the searchDocs property.
     * 
     * @return
     *     possible object is
     *     {@link SearchDocs }
     *     
     */
    public SearchDocs getSearchDocs() {
        return searchDocs;
    }

    /**
     * Sets the value of the searchDocs property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchDocs }
     *     
     */
    public void setSearchDocs(SearchDocs value) {
        this.searchDocs = value;
    }

    /**
     * Gets the value of the entityCollection property.
     * 
     * @return
     *     possible object is
     *     {@link EntityCollection }
     *     
     */
    public EntityCollection getEntityCollection() {
        return entityCollection;
    }

    /**
     * Sets the value of the entityCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityCollection }
     *     
     */
    public void setEntityCollection(EntityCollection value) {
        this.entityCollection = value;
    }

}
