/**
 * Mule QuickBooks Connector
 *
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.15 at 05:31:44 PM GMT-03:00 
//


package org.mule.modules.quickbooks.windows.schema;

import java.io.Serializable;
import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.mule.modules.quickbooks.utils.QBDateAdapter;


/**
 * 
 *         Product: QBW
 *         Description: sync status detail down to object ID and error message
 *       
 * 
 * <p>Java class for SyncStatusDrillDown complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SyncStatusDrillDown">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SyncEventId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SyncTMS" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="EntityId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RequestId" type="{http://www.intuit.com/sb/cdm/v2}guid" minOccurs="0"/>
 *         &lt;element name="NgObjectType" type="{http://www.intuit.com/sb/cdm/v2}objectName" minOccurs="0"/>
 *         &lt;element name="OperationType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SyncMessageCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SyncMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SyncStatusDrillDown", propOrder = {
    "syncEventId",
    "syncTMS",
    "entityId",
    "requestId",
    "ngObjectType",
    "operationType",
    "syncMessageCode",
    "syncMessage"
})
public class SyncStatusDrillDown
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "SyncEventId")
    protected String syncEventId;
    @XmlElement(name = "SyncTMS", type = String.class)
    @XmlJavaTypeAdapter(QBDateAdapter.class)
    @XmlSchemaType(name = "dateTime")
    protected Date syncTMS;
    @XmlElement(name = "EntityId")
    protected String entityId;
    @XmlElement(name = "RequestId")
    protected String requestId;
    @XmlElement(name = "NgObjectType")
    protected ObjectName ngObjectType;
    @XmlElement(name = "OperationType")
    protected String operationType;
    @XmlElement(name = "SyncMessageCode")
    protected String syncMessageCode;
    @XmlElement(name = "SyncMessage")
    protected String syncMessage;

    /**
     * Gets the value of the syncEventId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSyncEventId() {
        return syncEventId;
    }

    /**
     * Sets the value of the syncEventId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSyncEventId(String value) {
        this.syncEventId = value;
    }

    /**
     * Gets the value of the syncTMS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getSyncTMS() {
        return syncTMS;
    }

    /**
     * Sets the value of the syncTMS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSyncTMS(Date value) {
        this.syncTMS = value;
    }

    /**
     * Gets the value of the entityId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityId() {
        return entityId;
    }

    /**
     * Sets the value of the entityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityId(String value) {
        this.entityId = value;
    }

    /**
     * Gets the value of the requestId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestId(String value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the ngObjectType property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectName }
     *     
     */
    public ObjectName getNgObjectType() {
        return ngObjectType;
    }

    /**
     * Sets the value of the ngObjectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectName }
     *     
     */
    public void setNgObjectType(ObjectName value) {
        this.ngObjectType = value;
    }

    /**
     * Gets the value of the operationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * Sets the value of the operationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationType(String value) {
        this.operationType = value;
    }

    /**
     * Gets the value of the syncMessageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSyncMessageCode() {
        return syncMessageCode;
    }

    /**
     * Sets the value of the syncMessageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSyncMessageCode(String value) {
        this.syncMessageCode = value;
    }

    /**
     * Gets the value of the syncMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSyncMessage() {
        return syncMessage;
    }

    /**
     * Sets the value of the syncMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSyncMessage(String value) {
        this.syncMessage = value;
    }

}
